// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6oEwBDrLbX7INjuH5G8lZq_6sx5bAcnQ',
    appId: '1:871460089461:web:6bb84f5f5a9ae6085b123c',
    messagingSenderId: '871460089461',
    projectId: 'lib-appdev-assignment-04',
    authDomain: 'lib-appdev-assignment-04.firebaseapp.com',
    storageBucket: 'lib-appdev-assignment-04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgB9Sqig7jlpkGULxdG2YnodhOKgSKq4E',
    appId: '1:871460089461:android:4bb6617e43ef4c955b123c',
    messagingSenderId: '871460089461',
    projectId: 'lib-appdev-assignment-04',
    storageBucket: 'lib-appdev-assignment-04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBWzurUbIsIlgmqVhPhBSX68iI11oIs-U',
    appId: '1:871460089461:ios:0975f3fdcc167fc55b123c',
    messagingSenderId: '871460089461',
    projectId: 'lib-appdev-assignment-04',
    storageBucket: 'lib-appdev-assignment-04.appspot.com',
    iosClientId: '871460089461-iha45bsa4gcti5q7qcsr77jo61nn8b8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.libAppdevAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBWzurUbIsIlgmqVhPhBSX68iI11oIs-U',
    appId: '1:871460089461:ios:0975f3fdcc167fc55b123c',
    messagingSenderId: '871460089461',
    projectId: 'lib-appdev-assignment-04',
    storageBucket: 'lib-appdev-assignment-04.appspot.com',
    iosClientId: '871460089461-iha45bsa4gcti5q7qcsr77jo61nn8b8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.libAppdevAssignment',
  );
}